# EasyCommandBlocker - плагин для легкой и удобной блокировки команд на сервере Minecraft
#Описание и инструкция: https://github.com/l1ratch/EasyCommandBlocker/tree/master#readme

deftxt: '&cЭта команда заблокирована!'

BlockCMD:
  - 'op', '&4Эта команда заблокирована администратором.', 'tabCompleter: true'
  - 'gm 1', 'deftxt', 'tabCompleter: false'
  - 'set time 1', ''  #
  - 'gamemode creative', '&eВы не можете менять режим игры.', 'tabCompleter: true'

