name: EasyCommandBlocker
version: '${project.version}'
main: org.l1ratch.easyCommandBlocker.EasyCommandBlocker
load: STARTUP
authors: [ l1ratch ]
description: Plugin for block commad(for minecraft spigot server)
